language: csharp
solution: Chemistry.sln
install:
  - nuget restore Chemistry.sln
  - nuget install NUnit.Console -OutputDirectory testrunner
script:
  - xbuild Chemistry.sln 
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Test/bin/Debug/Test.dll
